all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.88.41/29
metal:
  children:
    masters:
      hosts:
        jango1: {ansible_host: 192.168.88.41, mac: '6c:4b:90:9f:d1:3b', disk: sda, network_interface: eno1}
        jango2: {ansible_host: 192.168.88.42, mac: '6c:4b:90:93:6c:16', disk: sda, network_interface: eno1}
        jango3: {ansible_host: 192.168.88.43, mac: '6c:4b:90:9f:d1:1f', disk: sda, network_interface: eno1}
    workers:
      hosts:
        jango4: {ansible_host: 192.168.88.44, mac: '6c:4b:90:93:6c:c4', disk: sda, network_interface: eno1}
        jango5: {ansible_host: 192.168.88.45, mac: '6c:4b:90:9f:d1:45', disk: sda, network_interface: eno1}
