apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: &repoURL https://github.com/jonaskoperdraat/homelab
        revision: &revision master
        directories:
          - path: application/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        layer: application
    spec:
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      project: default  # TODO
      source:
        repoURL: *repoURL
        path: '{{path}}'
        targetRevision: *revision
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          annotations:
            # Enable privileged VolSync movers by default for all namespaces
            # TODO this may be refactored in the future for finer granularity
            # See also https://volsync.readthedocs.io/en/stable/usage/permissionmodel.html
            volsync.backube/privileged-movers: "true"
