apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: restore-prive
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: &repoURL ssh://git@git.yona.works:22/prive/argocd-apps
        revision: &revision main
        files:
          - path: application/restore/targets.yaml
  template:
    metadata:
      name: 'restore-prive-{{name}}'
      labels:
        layer: restore
        tenant: prive
    spec:
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      project: default  # TODO
      sources:
        - repoURL: *repoURL
          path: '{{chartPath}}'
          targetRevision: *revision
          helm:
            valueFiles:
              - values.yaml
              - values-restore.yaml
        - repoURL: *repoURL
          path: '{{chartPath}}/restore'
          targetRevision: *revision
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          annotations:
            volsync.backube/privileged-movers: "true"
