{{- if .Values.backupExportJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-export
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  schedule: "0 0 1 1 *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: gitea-shared-storage
            - name: dump
              persistentVolumeClaim:
                claimName: {{ .Values.dumpPvc.name }}
            - name: tmp
              emptyDir: {}
          containers:
            - name: export
              image: "{{ .Values.backupExportJob.image.repository }}:{{ .Values.backupExportJob.image.tag }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: GITEA_APP_INI
                  value: /data/gitea/conf/app.ini
                - name: GITEA_CUSTOM
                  value: /data/gitea
                - name: GITEA_WORK_DIR
                  value: /data
                - name: GITEA_TEMP
                  value: /tmp/gitea
                - name: TMPDIR
                  value: /tmp/gitea
                - name: HOME
                  value: /data/gitea/git
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: dump
                  mountPath: /dump
                - name: tmp
                  mountPath: /tmp
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail

                  echo "Running gitea dump..."
                  gitea_dump_ts="$(date -u +%Y%m%d%H%M%S)"
                  mkdir -p /tmp/gitea
                  mkdir -p /dump
                  rm -f /dump/gitea-dump-*.zip
                  gitea dump -c /data/gitea/conf/app.ini --file /dump/gitea-dump-${gitea_dump_ts}.zip
{{- end }}
