apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-janitor
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-janitor-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-janitor-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gitea-janitor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitea-janitor-role
  apiGroup: rbac.authorization.k8s.io
---