apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-janitor
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-janitor-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-janitor-cluster-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gitea-janitor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gitea-janitor-cluster-role
  apiGroup: rbac.authorization.k8s.io
---