apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-bot-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: ssh://git@git.yona.works:22/prive/argocd-apps
        sshPrivateKey: {{` "{{ .sshPrivateKey }}" `}}
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: external
        property: argocd-gitea-bot-private-key