apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - yona.works
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
      - selector:
          dnsZones:
            - jonaskoperdraat.nl
        dns01:
          webhook:
            groupName: acme.jonaskoperdraat.nl
            solverName: transip
            config:
              accountName:
                valueFrom:
                  secretKeyRef:
                    name: transip-private-key
                    key: account-name
              ttl: 300
              privateKeySecretRef:
                name: transip-private-key
                key: private-key

